version: "3.7"

services:
  db:
    container_name: postgres-db-3sigmas
    image: postgres:14.0-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      - POSTGRES_DB=GORM
      - POSTGRES_USER=GO
      - POSTGRES_PASSWORD=PASSWORD
    volumes:
      - ./db:/var/lib/postgresql/data