POST http://localhost:3001/api/v0/trigger/bucket/production.3s_230913.trimble

###
POST http://localhost:3001/api/v0/trigger/action/cc08b7fb-8a15-46a4-9654-5e85bce6edc1

###
DELETE localhost:3001/api/v0/action/cc08b7fb-8a15-46a4-9654-5e85bce6edc1
Accept: application/json

###
POST localhost:3001/api/v0/action
Accept: application/json
Content-Type: application/json

{
  "active": true,
  "equationName": "Addition",
  "listVariables": "KM_000_D,KM_000_G;",
  "bucketName": "production.3s_230913.trimble"
}

###
GET localhost:3001/api/v0/function
Accept: application/json

###
GET localhost:3001/api/v0/bucket
Accept: application/json

###
GET localhost:3001/api/v0/action
Accept: application/json

###
GET localhost:3001/api/v0/health


